name: Docker Image Build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
    - name: Cache
      uses: actions/cache@v4
      id: cache
      with:
        path: cache-mount
        key: cache-mount-${{ hashFiles('Dockerfile') }}
    - uses: actions/checkout@v4
    - name: Restore Docker cache mounts
      uses: reproducible-containers/buildkit-cache-dance@v3
      with:
        builder: ${{ steps.setup-buildx.outputs.name }}
        cache-dir: cache-mount
        dockerfile: Dockerfile
        skip-extraction: ${{ steps.cache.outputs.cache-hit }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
